=== mozilla/REALISE-Performance/data_annotation_platform/app/utils/dataset_schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://example.com/root.json",
	"type": "object",
	"title": "Dataset Schema",
	"default": null,
	"required": [
		"name",
		"n_obs",
		"n_dim",
		"time",
		"series"
	],
	"properties": {
		"name": {
			"$id": "#/properties/name",
			"type": "string",
			"title": "The Name Schema",
			"default": "",
			"pattern": "^[a-z0-9\\_]+$"
		},
		"longname": {
			"$id": "#/properties/longname",
			"type": "string",
			"title": "The Longname Schema",
			"default": "",
			"pattern": "^(.+)$"
		},
		"n_obs": {
			"$id": "#/properties/n_obs",
			"type": "integer",
			"title": "The N_obs Schema",
			"default": 0
		},
		"n_dim": {
			"$id": "#/properties/n_dim",
			"type": "integer",
			"title": "The N_dim Schema",
			"default": 0
		},
		"demo": {
			"$id": "#/properties/demo",
			"type": "object",
			"title": "The Demo Schema",
			"properties": {
				"true_CPs": {
					"$id": "#/properties/demo/properties/true_CPs",
					"type": "array",
					"items": {
						"$id": "#/properties/demo/properties/true_CPs/items",
						"type": "integer",
						"title": "The Items Schema",
						"default": null
					}
				}
			}
		},
		"time": {
			"$id": "#/properties/time",
			"type": "object",
			"title": "The Time Schema",
			"default": null,
			"required": [
				"index"
			],
			"properties": {
				"format": {
					"$id": "#/properties/time/properties/format",
					"type": "string",
					"title": "The Format Schema",
					"default": "",
					"pattern": "^(.*)$"
				},
				"index": {
					"$id": "#/properties/time/properties/index",
					"type": "array",
					"title": "Integer index of the series, starting from 0.",
					"items": {
						"$id": "#/properties/time/properties/index/items",
						"type": "integer",
						"title": "The index items schema",
						"default": null
					}
				},
				"raw": {
					"$id": "#/properties/time/properties/raw",
					"type": "array",
					"title": "The Raw Schema",
					"items": {
						"$id": "#/properties/time/properties/raw/items",
						"type": "string",
						"title": "The Items Schema",
						"default": ""
					}
				}
			}
		},
		"series": {
			"$id": "#/properties/series",
			"type": "array",
			"title": "The Series Schema",
			"items": {
				"$id": "#/properties/series/items",
				"type": "object",
				"title": "The Variable Schema",
				"default": null,
				"properties": {
					"label": {
						"$id": "#/properties/series/items/properties/label",
						"type": "string",
						"title": "The Label Schema",
						"default": "",
						"pattern": "^(.+)$"
					},
					"type": {
						"$id": "#/properties/series/items/properties/type",
						"type": "string",
						"title": "The Type Schema",
						"default": "",
						"pattern": "^(.+)$"
					},
					"raw": {
						"$id": "#/properties/series/items/properties/raw",
						"type": "array",
						"title": "The Raw Schema",
						"items": {
							"$id": "#/properties/series/items/properties/raw/items",
							"title": "The Items Schema",
							"default": 0
						}
					}
				},
				"required": [
					"type",
					"raw"
				]
			}
		}
	}
}

=== mozilla/REALISE-Performance/project1/datasets-json/autoland2/4610295.json
{
    "name": "4610295",
    "longname": "4610295 timeseries",
    "n_obs": 134,
    "n_dim": 1,
    "time": {
        "type": "string",
        "format": "%Y-%m-%d %H:%M:%S",
        "index": [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72,
            73,
            74,
            75,
            76,
            77,
            78,
            79,
            80,
            81,
            82,
            83,
            84,
            85,
            86,
            87,
            88,
            89,
            90,
            91,
            92,
            93,
            94,
            95,
            96,
            97,
            98,
            99,
            100,
            101,
            102,
            103,
            104,
            105,
            106,
            107,
            108,
            109,
            110,
            111,
            112,
            113,
            114,
            115,
            116,
            117,
            118,
            119,
            120,
            121,
            122,
            123,
            124,
            125,
            126,
            127,
            128,
            129,
            130,
            131,
            132,
            133
        ],
        "raw": [
            "2023-05-24 10:49:25",
            "2023-05-24 13:34:40",
            "2023-05-24 17:26:23",
            "2023-05-24 21:30:03",
            "2023-05-25 01:52:13",
            "2023-05-25 06:53:28",
            "2023-05-25 09:03:58",
            "2023-05-25 13:17:19",
            "2023-05-25 13:25:13",
            "2023-05-25 17:00:24",
            "2023-05-25 20:49:35",
            "2023-05-26 00:58:32",
            "2023-05-26 04:58:44",
            "2023-05-26 08:30:04",
            "2023-05-26 12:58:50",
            "2023-05-26 13:11:40",
            "2023-05-26 17:23:29",
            "2023-05-26 18:57:45",
            "2023-05-26 19:09:08",
            "2023-05-26 19:44:57",
            "2023-05-27 00:56:39",
            "2023-05-27 11:39:36",
            "2023-05-27 15:52:21",
            "2023-05-28 20:46:15",
            "2023-05-29 02:12:22",
            "2023-05-29 06:50:24",
            "2023-05-29 07:27:55",
            "2023-05-29 13:34:49",
            "2023-05-29 15:52:56",
            "2023-05-29 20:27:32",
            "2023-05-29 20:34:18",
            "2023-05-30 01:15:28",
            "2023-05-30 06:58:06",
            "2023-05-30 07:49:46",
            "2023-05-30 12:05:20",
            "2023-05-30 14:11:57",
            "2023-05-30 14:17:42",
            "2023-05-30 14:18:36",
            "2023-05-30 14:20:30",
            "2023-05-30 15:20:14",
            "2023-05-30 17:40:00",
            "2023-05-30 18:28:22",
            "2023-05-30 19:20:55",
            "2023-05-30 19:21:44",
            "2023-05-30 22:16:30",
            "2023-05-31 02:21:54",
            "2023-05-31 09:56:26",
            "2023-05-31 12:33:14",
            "2023-05-31 12:40:08",
            "2023-05-31 14:02:33",
            "2023-05-31 15:08:35",
            "2023-05-31 17:22:12",
            "2023-05-31 20:28:19",
            "2023-05-31 21:52:05",
            "2023-05-31 21:52:58",
            "2023-05-31 23:35:37",
            "2023-06-01 03:44:27",
            "2023-06-01 08:18:01",
            "2023-06-01 09:51:53",
            "2023-06-01 13:54:39",
            "2023-06-01 19:53:44",
            "2023-06-01 21:35:55",
            "2023-06-02 02:04:00",
            "2023-06-02 12:19:13",
            "2023-06-02 13:27:34",
            "2023-06-02 17:59:13",
            "2023-06-02 18:03:52",
            "2023-06-02 22:18:32",
            "2023-06-03 05:40:17",
            "2023-06-03 14:24:38",
            "2023-06-03 23:39:13",
            "2023-06-04 11:53:44",
            "2023-06-04 20:28:08",
            "2023-06-05 03:24:10",
            "2023-06-05 08:05:57",
            "2023-06-05 08:13:54",
            "2023-06-05 09:41:40",
            "2023-06-05 09:45:03",
            "2023-06-05 10:13:11",
            "2023-06-05 11:51:57",
            "2023-06-05 12:01:26",
            "2023-06-05 16:13:31",
            "2023-06-05 16:43:43",
            "2023-06-05 20:14:05",
            "2023-06-05 22:25:10",
            "2023-06-06 02:16:37",
            "2023-06-06 04:54:44",
            "2023-06-06 04:54:44",
            "2023-06-06 04:54:44",
            "2023-06-06 04:54:44",
            "2023-06-06 04:54:44",
            "2023-06-06 06:34:52",
            "2023-06-06 06:34:52",
            "2023-06-06 06:34:52",
            "2023-06-06 06:34:52",
            "2023-06-06 06:34:52",
            "2023-06-06 06:39:51",
            "2023-06-06 06:39:51",
            "2023-06-06 06:39:51",
            "2023-06-06 06:39:51",
            "2023-06-06 06:39:51",
            "2023-06-06 06:39:51",
            "2023-06-06 06:39:51",
            "2023-06-06 06:39:51",
            "2023-06-06 06:39:51",
            "2023-06-06 06:39:51",
            "2023-06-06 06:46:10",
            "2023-06-06 06:46:10",
            "2023-06-06 06:46:10",
            "2023-06-06 06:46:10",
            "2023-06-06 06:46:10",
            "2023-06-06 06:46:10",
            "2023-06-06 06:46:10",
            "2023-06-06 06:46:10",
            "2023-06-06 06:46:10",
            "2023-06-06 06:46:10",
            "2023-06-06 06:54:33",
            "2023-06-06 06:54:33",
            "2023-06-06 06:54:33",
            "2023-06-06 06:54:33",
            "2023-06-06 06:54:33",
            "2023-06-06 06:54:33",
            "2023-06-06 07:00:26",
            "2023-06-06 07:00:26",
            "2023-06-06 07:00:26",
            "2023-06-06 07:00:26",
            "2023-06-06 07:00:26",
            "2023-06-06 07:00:26",
            "2023-06-06 07:23:00",
            "2023-06-06 07:23:00",
            "2023-06-06 07:23:00",
            "2023-06-06 07:23:00",
            "2023-06-06 07:23:00",
            "2023-06-06 07:23:00"
        ]
    },
    "series": [
        {
            "label": "Timeseries",
            "type": "float",
            "raw": [
                791.1,
                794.4,
                773.1,
                776.0,
                778.0,
                775.8,
                792.1,
                787.4,
                788.9,
                792.2,
                795.5,
                788.2,
                779.5,
                789.9,
                769.5,
                781.6,
                791.7,
                780.1,
                784.6,
                774.1,
                786.0,
                772.1,
                792.3,
                781.1,
                788.4,
                789.1,
                789.9,
                789.8,
                796.2,
                792.3,
                778.2,
                782.4,
                783.5,
                784.7,
                781.6,
                766.9,
                791.4,
                793.2,
                806.3,
                765.1,
                796.7,
                788.5,
                785.5,
                801.5,
                805.4,
                784.7,
                789.1,
                800.7,
                789.1,
                781.9,
                787.1,
                784.1,
                770.8,
                791.9,
                783.9,
                778.1,
                777.4,
                765.9,
                788.9,
                795.6,
                793.8,
                787.2,
                782.6,
                796.4,
                785.2,
                789.5,
                798.3,
                779.1,
                785.2,
                782.3,
                780.6,
                784.4,
                791.3,
                764.4,
                781.8,
                781.0,
                795.4,
                768.3,
                796.5,
                807.9,
                794.6,
                800.8,
                784.3,
                789.5,
                782.0,
                802.3,
                799.7,
                803.9,
                785.7,
                802.9,
                776.2,
                793.9,
                787.3,
                781.1,
                783.6,
                795.8,
                787.3,
                810.9,
                804.4,
                788.3,
                781.2,
                784.2,
                777.7,
                776.1,
                798.1,
                796.7,
                777.4,
                797.1,
                783.2,
                802.7,
                802.2,
                802.7,
                785.0,
                778.5,
                796.5,
                772.3,
                775.2,
                796.8,
                789.4,
                793.0,
                796.1,
